// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:bb103896-c351-4045-81ad-853de0071839',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'foldappsync-hosting-mobilehub-301964397',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2yg1pqypfzc9q.cloudfront.net',
    'aws_google_app_permissions': 'email,profile,openid',
    'aws_google_web_app_id': '431648118408-eba6o4rsi5b5ltr8ujcmbmcvjcm6t7gc.apps.googleusercontent.com',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '7406c3180ffe49a988debe6965f4f9c5',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'fbda90f2-b6c0-40fb-8be6-6f996b64f1e5',
    'aws_project_name': 'fold-appsync',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'foldappsync-mobilehub-301964397',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_GhO9ocbq2',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '2bonp9g49d5v7t976i0qkaaq4l',
    'aws_appsync_graphqlEndpoint': 'https://qo4zkrab3ncrxnqfldwp3idmhm.appsync-api.us-east-1.amazonaws.com/graphql',
    'aws_appsync_region': 'us-east-1',
    'aws_appsync_authenticationType': 'AWS_IAM',
}

export default awsmobile;
